[package]
name = "tc"
version = "0.7.3"
edition = "2021"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.9.25"
log = "0.4"
toml = "0.8.8"
open = "5.0.0"
derivative = "2.2.0"
walkdir = "2"
glob = "0.3.1"
tabled = "0.10.0"
ptree = "0.4.0"
clap = { version = "4.1", features = ["derive"] }
openssl = { version = "0.10", features = ["vendored"] }
colored = "2.0.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
anyhow = "1.0.71"
config-file = "0.2.3"
kit =  { path = "lib/kit" }
git =  { path = "lib/git" }
github =  { path = "lib/github" }
aws =  { path = "lib/aws" }
notifier =  { path = "lib/notifier" }

[dev-dependencies]
mockall = "0.12.1"

[workspace]
members = [
   "lib/kit",
   "lib/git",
   "lib/github",
   "lib/notifier",
   "lib/aws"
]

[profile.release]
opt-level = 's'
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
incremental = false
overflow-checks = true
strip = true
