name: Build
on:
  push:
    tags:
      - "*"
env:
  PROJECT_NAME: tc

permissions:
  contents: write
  pull-requests: write
  issues: read
  packages: none

jobs:
  build:
    # Set the job to run on the platform specified by the matrix below
    runs-on: ${{ matrix.runner }}

    # Define the build matrix for cross-compilation
    strategy:
      matrix:
        include:
          - name: tc-x86_64-linux
            runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - name:  tc-aarch64-macos
            runner: macos-latest
            target: aarch64-apple-darwin

    # The steps to run for each matrix item
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: "${{ matrix.target }}"

      - name: Setup Cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/tc
          asset_name: ${{ matrix.name }}
          tag: ${{ github.ref }}
